name = "small-thunder-6298"
account_id = "d902b91f0f1076e0601ffd6e7b4382c0"
main = "src/worker.js"
compatibility_date = "2025-04-01"
workers_dev = true
minify = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV_DATA"
id = "6f3cf17d2c6a433ba21c2d228069db66"

[triggers]
crons = ["0 8 * * *"]

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "changeme"
SESSION_SECRET = "super-secret-session-key-change-in-production"
ADMIN_UUID = "84621b0a-14e1-4600-ad46-aec6bcfa0e14"
