function E(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function A(s){return E(s).replace(/'/g,'&#39;')}
function H(t,b){return '<!DOCTYPE html><html><head><title>'+t+'</title><meta name=viewport content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{font-family:system-ui;background:#0f172a;color:#e2e8f0;margin:0;padding:1rem}input,button{font-family:inherit}.c{max-width:64rem;margin:0 auto}a{color:#93c5fd}</style></head><body>'+b+'</body></html>'}

export function loginPage(bp,err=''){
  return H('Login','<div style="max-width:24rem;margin:4rem auto;text-align:center"><h1>Edge Gateway</h1><p style=color:#94a3b8>Secure Console</p>'+(err?'<p style=color:#f87171>'+E(err)+'</p>':'')+'<form method=POST action="'+E(bp)+'/login" style="display:flex;flex-direction:column;gap:.75rem;margin-top:1.5rem"><input name=username required placeholder=Username style="padding:.5rem;background:#1e293b;border:1px solid #334155;border-radius:.5rem;color:#e2e8f0"><input name=password type=password required placeholder=Password style="padding:.5rem;background:#1e293b;border:1px solid #334155;border-radius:.5rem;color:#e2e8f0"><button type=submit style="padding:.5rem;background:#7c3aed;color:white;border:none;border-radius:.5rem;cursor:pointer">Sign In</button></form></div>')}

export function dashboardPage(bp,o){
  var c=o.config||{},nc=o.notifyConfig||{},ks=o.keys||[],h=o.host||'',m=o.message||'',mt=o.messageType||'success';
  var B=E(bp),uuid=c.uuid||'',ips=Array.isArray(c.cleanIps)?c.cleanIps:[],pts=Array.isArray(c.ports)?c.ports:[443];
  var toast=m?'<div style="position:fixed;top:1rem;right:1rem;padding:.75rem 1.25rem;border-radius:.5rem;background:'+(mt==='error'?'rgba(239,68,68,.2)':'rgba(16,185,129,.2)')+';color:'+(mt==='error'?'#fca5a5':'#6ee7b7')+'">'+E(m)+'</div>':'';

  var uris='';for(var ip of ips)for(var port of pts){var u='vless://'+uuid+'@'+ip+':'+port+'?encryption=none&security=tls&sni='+h+'&type=ws&host='+h+'&fp=chrome#'+encodeURIComponent(ip+':'+port);uris+='<div style="padding:.5rem;background:#1e293b;border-radius:.5rem;margin-bottom:.25rem;font-family:monospace;font-size:.75rem;color:#c4b5fd;word-break:break-all">'+E(u)+'</div>'}

  var kvRows=ks.map(function(k){return '<tr><td style="padding:.5rem;font-family:monospace;color:#c4b5fd">'+E(k.name)+'</td><td style=padding:.5rem><a href="'+B+'/kv/get?key='+encodeURIComponent(k.name)+'">View</a></td></tr>'}).join('')||'<tr><td colspan=2 style="padding:1rem;text-align:center;color:#64748b">No keys</td></tr>';

  return H('Edge Gateway',toast+'<div class=c><header style="display:flex;justify-content:space-between;align-items:center;padding:1rem 0;border-bottom:1px solid #1e293b"><div><strong>Edge Gateway</strong> <span style="font-size:.75rem;color:#64748b">'+E(h)+'</span></div><a href="'+B+'/logout" style="font-size:.875rem">Logout</a></header>'+
  '<h2 style=margin-top:1.5rem>Configuration</h2><form method=POST action="'+B+'/config" style="display:flex;flex-direction:column;gap:.5rem"><label>VLESS UUID<input name=uuid value="'+A(uuid)+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0;font-family:monospace"></label><label>Proxy IP<input name=proxyIp value="'+A(c.proxyIp||'')+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0;font-family:monospace"></label><label>Clean IPs<input name=cleanIps value="'+A(ips.join(', '))+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0;font-family:monospace"></label><label>Ports<input name=ports value="'+A(pts.join(', '))+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0;font-family:monospace"></label><label>Proxy Target<input name=proxyTarget value="'+A(c.proxyTarget||'')+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0;font-family:monospace"></label><button type=submit style="padding:.5rem;background:#7c3aed;color:white;border:none;border-radius:.375rem;cursor:pointer;align-self:start">Save</button></form>'+
  '<h2 style=margin-top:1.5rem>Connection Strings</h2>'+(uris||'<p style=color:#64748b>No IPs configured</p>')+
  '<h2 style=margin-top:1.5rem>Notifications</h2><form method=POST action="'+B+'/notify-settings" style="display:flex;flex-direction:column;gap:.5rem"><label>Email<input name=email value="'+A(nc.email||'amin.chinisaz@gmail.com')+'" type=email style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"></label><label><input type=checkbox name=emailEnabled '+(nc.emailEnabled?'checked':'')+'>Email enabled</label><label>Telegram Bot Token<input name=telegramBotToken value="'+A(nc.telegramBotToken||'')+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"></label><label>Telegram Chat ID<input name=telegramChatId value="'+A(nc.telegramChatId||'')+'" style="width:100%;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"></label><label><input type=checkbox name=telegramEnabled '+(nc.telegramEnabled?'checked':'')+'>Telegram enabled</label><button type=submit style="padding:.5rem;background:#7c3aed;color:white;border:none;border-radius:.375rem;cursor:pointer;align-self:start">Save Notifications</button></form>'+
  '<div style="display:flex;gap:.5rem;margin-top:1rem"><form method=POST action="'+B+'/notify-send"><input type=hidden name=channel value=email><button style="padding:.5rem 1rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#93c5fd;cursor:pointer">Send Email</button></form><form method=POST action="'+B+'/notify-send"><input type=hidden name=channel value=telegram><button style="padding:.5rem 1rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#93c5fd;cursor:pointer">Send Telegram</button></form></div>'+
  '<h2 style=margin-top:1.5rem>KV Store</h2><form method=POST action="'+B+'/kv/put" style="display:flex;gap:.5rem;margin-bottom:1rem"><input name=key required placeholder=key style="flex:1;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"><input name=value required placeholder=value style="flex:2;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"><input name=ttl type=number placeholder=TTL style="width:5rem;padding:.375rem;background:#1e293b;border:1px solid #334155;border-radius:.375rem;color:#e2e8f0"><button type=submit style="padding:.375rem .75rem;background:#7c3aed;color:white;border:none;border-radius:.375rem;cursor:pointer">Add</button></form><table style=width:100%><tbody>'+kvRows+'</tbody></table></div>')}

export function viewValuePage(bp,key,val){
  return H('View: '+E(key),'<div class=c><h2>'+E(key)+'</h2><pre style="background:#1e293b;padding:1rem;border-radius:.5rem;white-space:pre-wrap;word-break:break-all;font-family:monospace">'+(val!==null?E(val):'<em style=color:#64748b>not found</em>')+'</pre><a href="'+E(bp)+'/dashboard">&larr; Back</a></div>')}
